[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'With ❤️ From <a class="text-muted" href="https://gethyas.com/">Bot Studio Chatbot Maker</a>'
    alertText = 'This website is a part of <a class="alert-link stretched-link fw-normal" href="https://www.botstudioo.com">Bot Studio Chatbot Maker</a>!'