[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Bot Studio Hub <span class="mx-1">&#x2764;</span> From <a class="text-muted" href="https://www.botstudioo.com/">Bot Studio Robot Maker</a>'
    alertText = 'This website is a part of <a class="alert-link stretched-link fw-normal" href="https://www.botstudioo.com">Bot Studio Robot Maker</a>!'